# Generated by Django 5.2.7 on 2025-11-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_submission_submitted_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='material',
            field=models.FileField(blank=True, null=True, upload_to='lessons/materials/'),
        ),
    ]
