# Generated by Django 5.2.7 on 2025-11-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('hard', 'Hard')], max_length=20, null=True),
        ),
    ]
