# Generated by Django 5.2.7 on 2025-11-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_enrollment_is_approved_alter_course_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='relative_due_days',
            field=models.PositiveIntegerField(default=7, help_text='Days after enrollment this assignment is due'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_days',
            field=models.PositiveIntegerField(default=30, help_text='Course access duration (in days) after enrollment'),
        ),
    ]
