# Generated by Django 5.2.7 on 2025-11-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_assignment_relative_due_days_course_duration_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='due_date',
        ),
    ]
